### ISSUE TITLE
Minor fix host mysql

### ISSUE THREAD

**Issue by asosso** [ikajaste/Joomla-2.5-Asset-Weaver#7]
Hi,

I wanted to suggest a small fix to your script
# Edit line 58 and 126:

$dbc = mysql_connect('localhost',$user,$pwd);
# with

$dbc = mysql_connect($host,$user,$pwd);
# Search this line

$conf = new JConfig();
# and add after

$host = $conf->host;
# Search this line

} elseif (isset($mosConfig_db)) {
# and add after

$host = $mosConfig_host;

**Comment by ikajaste** [comment]
Yes, you are quite correct, the host should be configurable. You missed a few lines though, the reconnection and command line parameters. I made the change in ee8efdf3b532e0eedbf78fa459beb7a18d5813b6
